  import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './index.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

// ? Session 3
// Fetching data
  // ! ^ We're facing a big problem here, we're not really fetching data, we're just statically rendering it on the server side every time.
// Backend routes
  //todo: Since we can't (shouldn't) run server-side code on client components, we need to create a backend route, we can do that with nextjs

// ? Session 4
// Mutating data (Create, Update, Delete)
// done Creating: POST - Create a new book
// done Upating: PUT - Update a book
// done Deleting: DELETE - Delete a book

// Global State
